/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.kkworld.futuresservice.cmsTrade;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CThostFtdcExchangeMarginRateField implements org.apache.thrift.TBase<CThostFtdcExchangeMarginRateField, CThostFtdcExchangeMarginRateField._Fields>, java.io.Serializable, Cloneable, Comparable<CThostFtdcExchangeMarginRateField> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CThostFtdcExchangeMarginRateField");

  private static final org.apache.thrift.protocol.TField BROKER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("brokerID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INSTRUMENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("instrumentID", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField HEDGE_FLAG_FIELD_DESC = new org.apache.thrift.protocol.TField("hedgeFlag", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField LONG_MARGIN_RATIO_BY_MONEY_FIELD_DESC = new org.apache.thrift.protocol.TField("longMarginRatioByMoney", org.apache.thrift.protocol.TType.DOUBLE, (short)4);
  private static final org.apache.thrift.protocol.TField LONG_MARGIN_RATIO_BY_VOLUME_FIELD_DESC = new org.apache.thrift.protocol.TField("longMarginRatioByVolume", org.apache.thrift.protocol.TType.DOUBLE, (short)5);
  private static final org.apache.thrift.protocol.TField SHORT_MARGIN_RATIO_BY_MONEY_FIELD_DESC = new org.apache.thrift.protocol.TField("shortMarginRatioByMoney", org.apache.thrift.protocol.TType.DOUBLE, (short)6);
  private static final org.apache.thrift.protocol.TField SHORT_MARGIN_RATIO_BY_VOLUME_FIELD_DESC = new org.apache.thrift.protocol.TField("shortMarginRatioByVolume", org.apache.thrift.protocol.TType.DOUBLE, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CThostFtdcExchangeMarginRateFieldStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CThostFtdcExchangeMarginRateFieldTupleSchemeFactory());
  }

  public String brokerID; // required
  public String instrumentID; // required
  public String hedgeFlag; // required
  public double longMarginRatioByMoney; // required
  public double longMarginRatioByVolume; // required
  public double shortMarginRatioByMoney; // required
  public double shortMarginRatioByVolume; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BROKER_ID((short)1, "brokerID"),
    INSTRUMENT_ID((short)2, "instrumentID"),
    HEDGE_FLAG((short)3, "hedgeFlag"),
    LONG_MARGIN_RATIO_BY_MONEY((short)4, "longMarginRatioByMoney"),
    LONG_MARGIN_RATIO_BY_VOLUME((short)5, "longMarginRatioByVolume"),
    SHORT_MARGIN_RATIO_BY_MONEY((short)6, "shortMarginRatioByMoney"),
    SHORT_MARGIN_RATIO_BY_VOLUME((short)7, "shortMarginRatioByVolume");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BROKER_ID
          return BROKER_ID;
        case 2: // INSTRUMENT_ID
          return INSTRUMENT_ID;
        case 3: // HEDGE_FLAG
          return HEDGE_FLAG;
        case 4: // LONG_MARGIN_RATIO_BY_MONEY
          return LONG_MARGIN_RATIO_BY_MONEY;
        case 5: // LONG_MARGIN_RATIO_BY_VOLUME
          return LONG_MARGIN_RATIO_BY_VOLUME;
        case 6: // SHORT_MARGIN_RATIO_BY_MONEY
          return SHORT_MARGIN_RATIO_BY_MONEY;
        case 7: // SHORT_MARGIN_RATIO_BY_VOLUME
          return SHORT_MARGIN_RATIO_BY_VOLUME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LONGMARGINRATIOBYMONEY_ISSET_ID = 0;
  private static final int __LONGMARGINRATIOBYVOLUME_ISSET_ID = 1;
  private static final int __SHORTMARGINRATIOBYMONEY_ISSET_ID = 2;
  private static final int __SHORTMARGINRATIOBYVOLUME_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BROKER_ID, new org.apache.thrift.meta_data.FieldMetaData("brokerID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "TThostFtdcBrokerIDType")));
    tmpMap.put(_Fields.INSTRUMENT_ID, new org.apache.thrift.meta_data.FieldMetaData("instrumentID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "TThostFtdcInstrumentIDType")));
    tmpMap.put(_Fields.HEDGE_FLAG, new org.apache.thrift.meta_data.FieldMetaData("hedgeFlag", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "TThostFtdcHedgeFlagType")));
    tmpMap.put(_Fields.LONG_MARGIN_RATIO_BY_MONEY, new org.apache.thrift.meta_data.FieldMetaData("longMarginRatioByMoney", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE        , "TThostFtdcRatioType")));
    tmpMap.put(_Fields.LONG_MARGIN_RATIO_BY_VOLUME, new org.apache.thrift.meta_data.FieldMetaData("longMarginRatioByVolume", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE        , "TThostFtdcMoneyType")));
    tmpMap.put(_Fields.SHORT_MARGIN_RATIO_BY_MONEY, new org.apache.thrift.meta_data.FieldMetaData("shortMarginRatioByMoney", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE        , "TThostFtdcRatioType")));
    tmpMap.put(_Fields.SHORT_MARGIN_RATIO_BY_VOLUME, new org.apache.thrift.meta_data.FieldMetaData("shortMarginRatioByVolume", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE        , "TThostFtdcMoneyType")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CThostFtdcExchangeMarginRateField.class, metaDataMap);
  }

  public CThostFtdcExchangeMarginRateField() {
  }

  public CThostFtdcExchangeMarginRateField(
    String brokerID,
    String instrumentID,
    String hedgeFlag,
    double longMarginRatioByMoney,
    double longMarginRatioByVolume,
    double shortMarginRatioByMoney,
    double shortMarginRatioByVolume)
  {
    this();
    this.brokerID = brokerID;
    this.instrumentID = instrumentID;
    this.hedgeFlag = hedgeFlag;
    this.longMarginRatioByMoney = longMarginRatioByMoney;
    setLongMarginRatioByMoneyIsSet(true);
    this.longMarginRatioByVolume = longMarginRatioByVolume;
    setLongMarginRatioByVolumeIsSet(true);
    this.shortMarginRatioByMoney = shortMarginRatioByMoney;
    setShortMarginRatioByMoneyIsSet(true);
    this.shortMarginRatioByVolume = shortMarginRatioByVolume;
    setShortMarginRatioByVolumeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CThostFtdcExchangeMarginRateField(CThostFtdcExchangeMarginRateField other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetBrokerID()) {
      this.brokerID = other.brokerID;
    }
    if (other.isSetInstrumentID()) {
      this.instrumentID = other.instrumentID;
    }
    if (other.isSetHedgeFlag()) {
      this.hedgeFlag = other.hedgeFlag;
    }
    this.longMarginRatioByMoney = other.longMarginRatioByMoney;
    this.longMarginRatioByVolume = other.longMarginRatioByVolume;
    this.shortMarginRatioByMoney = other.shortMarginRatioByMoney;
    this.shortMarginRatioByVolume = other.shortMarginRatioByVolume;
  }

  public CThostFtdcExchangeMarginRateField deepCopy() {
    return new CThostFtdcExchangeMarginRateField(this);
  }

  @Override
  public void clear() {
    this.brokerID = null;
    this.instrumentID = null;
    this.hedgeFlag = null;
    setLongMarginRatioByMoneyIsSet(false);
    this.longMarginRatioByMoney = 0.0;
    setLongMarginRatioByVolumeIsSet(false);
    this.longMarginRatioByVolume = 0.0;
    setShortMarginRatioByMoneyIsSet(false);
    this.shortMarginRatioByMoney = 0.0;
    setShortMarginRatioByVolumeIsSet(false);
    this.shortMarginRatioByVolume = 0.0;
  }

  public String getBrokerID() {
    return this.brokerID;
  }

  public CThostFtdcExchangeMarginRateField setBrokerID(String brokerID) {
    this.brokerID = brokerID;
    return this;
  }

  public void unsetBrokerID() {
    this.brokerID = null;
  }

  /** Returns true if field brokerID is set (has been assigned a value) and false otherwise */
  public boolean isSetBrokerID() {
    return this.brokerID != null;
  }

  public void setBrokerIDIsSet(boolean value) {
    if (!value) {
      this.brokerID = null;
    }
  }

  public String getInstrumentID() {
    return this.instrumentID;
  }

  public CThostFtdcExchangeMarginRateField setInstrumentID(String instrumentID) {
    this.instrumentID = instrumentID;
    return this;
  }

  public void unsetInstrumentID() {
    this.instrumentID = null;
  }

  /** Returns true if field instrumentID is set (has been assigned a value) and false otherwise */
  public boolean isSetInstrumentID() {
    return this.instrumentID != null;
  }

  public void setInstrumentIDIsSet(boolean value) {
    if (!value) {
      this.instrumentID = null;
    }
  }

  public String getHedgeFlag() {
    return this.hedgeFlag;
  }

  public CThostFtdcExchangeMarginRateField setHedgeFlag(String hedgeFlag) {
    this.hedgeFlag = hedgeFlag;
    return this;
  }

  public void unsetHedgeFlag() {
    this.hedgeFlag = null;
  }

  /** Returns true if field hedgeFlag is set (has been assigned a value) and false otherwise */
  public boolean isSetHedgeFlag() {
    return this.hedgeFlag != null;
  }

  public void setHedgeFlagIsSet(boolean value) {
    if (!value) {
      this.hedgeFlag = null;
    }
  }

  public double getLongMarginRatioByMoney() {
    return this.longMarginRatioByMoney;
  }

  public CThostFtdcExchangeMarginRateField setLongMarginRatioByMoney(double longMarginRatioByMoney) {
    this.longMarginRatioByMoney = longMarginRatioByMoney;
    setLongMarginRatioByMoneyIsSet(true);
    return this;
  }

  public void unsetLongMarginRatioByMoney() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LONGMARGINRATIOBYMONEY_ISSET_ID);
  }

  /** Returns true if field longMarginRatioByMoney is set (has been assigned a value) and false otherwise */
  public boolean isSetLongMarginRatioByMoney() {
    return EncodingUtils.testBit(__isset_bitfield, __LONGMARGINRATIOBYMONEY_ISSET_ID);
  }

  public void setLongMarginRatioByMoneyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LONGMARGINRATIOBYMONEY_ISSET_ID, value);
  }

  public double getLongMarginRatioByVolume() {
    return this.longMarginRatioByVolume;
  }

  public CThostFtdcExchangeMarginRateField setLongMarginRatioByVolume(double longMarginRatioByVolume) {
    this.longMarginRatioByVolume = longMarginRatioByVolume;
    setLongMarginRatioByVolumeIsSet(true);
    return this;
  }

  public void unsetLongMarginRatioByVolume() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LONGMARGINRATIOBYVOLUME_ISSET_ID);
  }

  /** Returns true if field longMarginRatioByVolume is set (has been assigned a value) and false otherwise */
  public boolean isSetLongMarginRatioByVolume() {
    return EncodingUtils.testBit(__isset_bitfield, __LONGMARGINRATIOBYVOLUME_ISSET_ID);
  }

  public void setLongMarginRatioByVolumeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LONGMARGINRATIOBYVOLUME_ISSET_ID, value);
  }

  public double getShortMarginRatioByMoney() {
    return this.shortMarginRatioByMoney;
  }

  public CThostFtdcExchangeMarginRateField setShortMarginRatioByMoney(double shortMarginRatioByMoney) {
    this.shortMarginRatioByMoney = shortMarginRatioByMoney;
    setShortMarginRatioByMoneyIsSet(true);
    return this;
  }

  public void unsetShortMarginRatioByMoney() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SHORTMARGINRATIOBYMONEY_ISSET_ID);
  }

  /** Returns true if field shortMarginRatioByMoney is set (has been assigned a value) and false otherwise */
  public boolean isSetShortMarginRatioByMoney() {
    return EncodingUtils.testBit(__isset_bitfield, __SHORTMARGINRATIOBYMONEY_ISSET_ID);
  }

  public void setShortMarginRatioByMoneyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SHORTMARGINRATIOBYMONEY_ISSET_ID, value);
  }

  public double getShortMarginRatioByVolume() {
    return this.shortMarginRatioByVolume;
  }

  public CThostFtdcExchangeMarginRateField setShortMarginRatioByVolume(double shortMarginRatioByVolume) {
    this.shortMarginRatioByVolume = shortMarginRatioByVolume;
    setShortMarginRatioByVolumeIsSet(true);
    return this;
  }

  public void unsetShortMarginRatioByVolume() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SHORTMARGINRATIOBYVOLUME_ISSET_ID);
  }

  /** Returns true if field shortMarginRatioByVolume is set (has been assigned a value) and false otherwise */
  public boolean isSetShortMarginRatioByVolume() {
    return EncodingUtils.testBit(__isset_bitfield, __SHORTMARGINRATIOBYVOLUME_ISSET_ID);
  }

  public void setShortMarginRatioByVolumeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SHORTMARGINRATIOBYVOLUME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BROKER_ID:
      if (value == null) {
        unsetBrokerID();
      } else {
        setBrokerID((String)value);
      }
      break;

    case INSTRUMENT_ID:
      if (value == null) {
        unsetInstrumentID();
      } else {
        setInstrumentID((String)value);
      }
      break;

    case HEDGE_FLAG:
      if (value == null) {
        unsetHedgeFlag();
      } else {
        setHedgeFlag((String)value);
      }
      break;

    case LONG_MARGIN_RATIO_BY_MONEY:
      if (value == null) {
        unsetLongMarginRatioByMoney();
      } else {
        setLongMarginRatioByMoney((Double)value);
      }
      break;

    case LONG_MARGIN_RATIO_BY_VOLUME:
      if (value == null) {
        unsetLongMarginRatioByVolume();
      } else {
        setLongMarginRatioByVolume((Double)value);
      }
      break;

    case SHORT_MARGIN_RATIO_BY_MONEY:
      if (value == null) {
        unsetShortMarginRatioByMoney();
      } else {
        setShortMarginRatioByMoney((Double)value);
      }
      break;

    case SHORT_MARGIN_RATIO_BY_VOLUME:
      if (value == null) {
        unsetShortMarginRatioByVolume();
      } else {
        setShortMarginRatioByVolume((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BROKER_ID:
      return getBrokerID();

    case INSTRUMENT_ID:
      return getInstrumentID();

    case HEDGE_FLAG:
      return getHedgeFlag();

    case LONG_MARGIN_RATIO_BY_MONEY:
      return Double.valueOf(getLongMarginRatioByMoney());

    case LONG_MARGIN_RATIO_BY_VOLUME:
      return Double.valueOf(getLongMarginRatioByVolume());

    case SHORT_MARGIN_RATIO_BY_MONEY:
      return Double.valueOf(getShortMarginRatioByMoney());

    case SHORT_MARGIN_RATIO_BY_VOLUME:
      return Double.valueOf(getShortMarginRatioByVolume());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BROKER_ID:
      return isSetBrokerID();
    case INSTRUMENT_ID:
      return isSetInstrumentID();
    case HEDGE_FLAG:
      return isSetHedgeFlag();
    case LONG_MARGIN_RATIO_BY_MONEY:
      return isSetLongMarginRatioByMoney();
    case LONG_MARGIN_RATIO_BY_VOLUME:
      return isSetLongMarginRatioByVolume();
    case SHORT_MARGIN_RATIO_BY_MONEY:
      return isSetShortMarginRatioByMoney();
    case SHORT_MARGIN_RATIO_BY_VOLUME:
      return isSetShortMarginRatioByVolume();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CThostFtdcExchangeMarginRateField)
      return this.equals((CThostFtdcExchangeMarginRateField)that);
    return false;
  }

  public boolean equals(CThostFtdcExchangeMarginRateField that) {
    if (that == null)
      return false;

    boolean this_present_brokerID = true && this.isSetBrokerID();
    boolean that_present_brokerID = true && that.isSetBrokerID();
    if (this_present_brokerID || that_present_brokerID) {
      if (!(this_present_brokerID && that_present_brokerID))
        return false;
      if (!this.brokerID.equals(that.brokerID))
        return false;
    }

    boolean this_present_instrumentID = true && this.isSetInstrumentID();
    boolean that_present_instrumentID = true && that.isSetInstrumentID();
    if (this_present_instrumentID || that_present_instrumentID) {
      if (!(this_present_instrumentID && that_present_instrumentID))
        return false;
      if (!this.instrumentID.equals(that.instrumentID))
        return false;
    }

    boolean this_present_hedgeFlag = true && this.isSetHedgeFlag();
    boolean that_present_hedgeFlag = true && that.isSetHedgeFlag();
    if (this_present_hedgeFlag || that_present_hedgeFlag) {
      if (!(this_present_hedgeFlag && that_present_hedgeFlag))
        return false;
      if (!this.hedgeFlag.equals(that.hedgeFlag))
        return false;
    }

    boolean this_present_longMarginRatioByMoney = true;
    boolean that_present_longMarginRatioByMoney = true;
    if (this_present_longMarginRatioByMoney || that_present_longMarginRatioByMoney) {
      if (!(this_present_longMarginRatioByMoney && that_present_longMarginRatioByMoney))
        return false;
      if (this.longMarginRatioByMoney != that.longMarginRatioByMoney)
        return false;
    }

    boolean this_present_longMarginRatioByVolume = true;
    boolean that_present_longMarginRatioByVolume = true;
    if (this_present_longMarginRatioByVolume || that_present_longMarginRatioByVolume) {
      if (!(this_present_longMarginRatioByVolume && that_present_longMarginRatioByVolume))
        return false;
      if (this.longMarginRatioByVolume != that.longMarginRatioByVolume)
        return false;
    }

    boolean this_present_shortMarginRatioByMoney = true;
    boolean that_present_shortMarginRatioByMoney = true;
    if (this_present_shortMarginRatioByMoney || that_present_shortMarginRatioByMoney) {
      if (!(this_present_shortMarginRatioByMoney && that_present_shortMarginRatioByMoney))
        return false;
      if (this.shortMarginRatioByMoney != that.shortMarginRatioByMoney)
        return false;
    }

    boolean this_present_shortMarginRatioByVolume = true;
    boolean that_present_shortMarginRatioByVolume = true;
    if (this_present_shortMarginRatioByVolume || that_present_shortMarginRatioByVolume) {
      if (!(this_present_shortMarginRatioByVolume && that_present_shortMarginRatioByVolume))
        return false;
      if (this.shortMarginRatioByVolume != that.shortMarginRatioByVolume)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CThostFtdcExchangeMarginRateField other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBrokerID()).compareTo(other.isSetBrokerID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBrokerID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.brokerID, other.brokerID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInstrumentID()).compareTo(other.isSetInstrumentID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInstrumentID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.instrumentID, other.instrumentID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHedgeFlag()).compareTo(other.isSetHedgeFlag());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHedgeFlag()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hedgeFlag, other.hedgeFlag);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLongMarginRatioByMoney()).compareTo(other.isSetLongMarginRatioByMoney());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongMarginRatioByMoney()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.longMarginRatioByMoney, other.longMarginRatioByMoney);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLongMarginRatioByVolume()).compareTo(other.isSetLongMarginRatioByVolume());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongMarginRatioByVolume()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.longMarginRatioByVolume, other.longMarginRatioByVolume);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetShortMarginRatioByMoney()).compareTo(other.isSetShortMarginRatioByMoney());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetShortMarginRatioByMoney()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.shortMarginRatioByMoney, other.shortMarginRatioByMoney);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetShortMarginRatioByVolume()).compareTo(other.isSetShortMarginRatioByVolume());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetShortMarginRatioByVolume()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.shortMarginRatioByVolume, other.shortMarginRatioByVolume);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CThostFtdcExchangeMarginRateField(");
    boolean first = true;

    sb.append("brokerID:");
    if (this.brokerID == null) {
      sb.append("null");
    } else {
      sb.append(this.brokerID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("instrumentID:");
    if (this.instrumentID == null) {
      sb.append("null");
    } else {
      sb.append(this.instrumentID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("hedgeFlag:");
    if (this.hedgeFlag == null) {
      sb.append("null");
    } else {
      sb.append(this.hedgeFlag);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("longMarginRatioByMoney:");
    sb.append(this.longMarginRatioByMoney);
    first = false;
    if (!first) sb.append(", ");
    sb.append("longMarginRatioByVolume:");
    sb.append(this.longMarginRatioByVolume);
    first = false;
    if (!first) sb.append(", ");
    sb.append("shortMarginRatioByMoney:");
    sb.append(this.shortMarginRatioByMoney);
    first = false;
    if (!first) sb.append(", ");
    sb.append("shortMarginRatioByVolume:");
    sb.append(this.shortMarginRatioByVolume);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CThostFtdcExchangeMarginRateFieldStandardSchemeFactory implements SchemeFactory {
    public CThostFtdcExchangeMarginRateFieldStandardScheme getScheme() {
      return new CThostFtdcExchangeMarginRateFieldStandardScheme();
    }
  }

  private static class CThostFtdcExchangeMarginRateFieldStandardScheme extends StandardScheme<CThostFtdcExchangeMarginRateField> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CThostFtdcExchangeMarginRateField struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BROKER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.brokerID = iprot.readString();
              struct.setBrokerIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INSTRUMENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.instrumentID = iprot.readString();
              struct.setInstrumentIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // HEDGE_FLAG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.hedgeFlag = iprot.readString();
              struct.setHedgeFlagIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LONG_MARGIN_RATIO_BY_MONEY
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.longMarginRatioByMoney = iprot.readDouble();
              struct.setLongMarginRatioByMoneyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LONG_MARGIN_RATIO_BY_VOLUME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.longMarginRatioByVolume = iprot.readDouble();
              struct.setLongMarginRatioByVolumeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // SHORT_MARGIN_RATIO_BY_MONEY
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.shortMarginRatioByMoney = iprot.readDouble();
              struct.setShortMarginRatioByMoneyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // SHORT_MARGIN_RATIO_BY_VOLUME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.shortMarginRatioByVolume = iprot.readDouble();
              struct.setShortMarginRatioByVolumeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CThostFtdcExchangeMarginRateField struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.brokerID != null) {
        oprot.writeFieldBegin(BROKER_ID_FIELD_DESC);
        oprot.writeString(struct.brokerID);
        oprot.writeFieldEnd();
      }
      if (struct.instrumentID != null) {
        oprot.writeFieldBegin(INSTRUMENT_ID_FIELD_DESC);
        oprot.writeString(struct.instrumentID);
        oprot.writeFieldEnd();
      }
      if (struct.hedgeFlag != null) {
        oprot.writeFieldBegin(HEDGE_FLAG_FIELD_DESC);
        oprot.writeString(struct.hedgeFlag);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LONG_MARGIN_RATIO_BY_MONEY_FIELD_DESC);
      oprot.writeDouble(struct.longMarginRatioByMoney);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LONG_MARGIN_RATIO_BY_VOLUME_FIELD_DESC);
      oprot.writeDouble(struct.longMarginRatioByVolume);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SHORT_MARGIN_RATIO_BY_MONEY_FIELD_DESC);
      oprot.writeDouble(struct.shortMarginRatioByMoney);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SHORT_MARGIN_RATIO_BY_VOLUME_FIELD_DESC);
      oprot.writeDouble(struct.shortMarginRatioByVolume);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CThostFtdcExchangeMarginRateFieldTupleSchemeFactory implements SchemeFactory {
    public CThostFtdcExchangeMarginRateFieldTupleScheme getScheme() {
      return new CThostFtdcExchangeMarginRateFieldTupleScheme();
    }
  }

  private static class CThostFtdcExchangeMarginRateFieldTupleScheme extends TupleScheme<CThostFtdcExchangeMarginRateField> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CThostFtdcExchangeMarginRateField struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBrokerID()) {
        optionals.set(0);
      }
      if (struct.isSetInstrumentID()) {
        optionals.set(1);
      }
      if (struct.isSetHedgeFlag()) {
        optionals.set(2);
      }
      if (struct.isSetLongMarginRatioByMoney()) {
        optionals.set(3);
      }
      if (struct.isSetLongMarginRatioByVolume()) {
        optionals.set(4);
      }
      if (struct.isSetShortMarginRatioByMoney()) {
        optionals.set(5);
      }
      if (struct.isSetShortMarginRatioByVolume()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetBrokerID()) {
        oprot.writeString(struct.brokerID);
      }
      if (struct.isSetInstrumentID()) {
        oprot.writeString(struct.instrumentID);
      }
      if (struct.isSetHedgeFlag()) {
        oprot.writeString(struct.hedgeFlag);
      }
      if (struct.isSetLongMarginRatioByMoney()) {
        oprot.writeDouble(struct.longMarginRatioByMoney);
      }
      if (struct.isSetLongMarginRatioByVolume()) {
        oprot.writeDouble(struct.longMarginRatioByVolume);
      }
      if (struct.isSetShortMarginRatioByMoney()) {
        oprot.writeDouble(struct.shortMarginRatioByMoney);
      }
      if (struct.isSetShortMarginRatioByVolume()) {
        oprot.writeDouble(struct.shortMarginRatioByVolume);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CThostFtdcExchangeMarginRateField struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.brokerID = iprot.readString();
        struct.setBrokerIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.instrumentID = iprot.readString();
        struct.setInstrumentIDIsSet(true);
      }
      if (incoming.get(2)) {
        struct.hedgeFlag = iprot.readString();
        struct.setHedgeFlagIsSet(true);
      }
      if (incoming.get(3)) {
        struct.longMarginRatioByMoney = iprot.readDouble();
        struct.setLongMarginRatioByMoneyIsSet(true);
      }
      if (incoming.get(4)) {
        struct.longMarginRatioByVolume = iprot.readDouble();
        struct.setLongMarginRatioByVolumeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.shortMarginRatioByMoney = iprot.readDouble();
        struct.setShortMarginRatioByMoneyIsSet(true);
      }
      if (incoming.get(6)) {
        struct.shortMarginRatioByVolume = iprot.readDouble();
        struct.setShortMarginRatioByVolumeIsSet(true);
      }
    }
  }

}

